### ISSUE TITLE
Configuration for rule "no-unused-vars" is invalid

### ISSUE THREAD

**Issue by geoangelotti** [kiprasmel/eslint-config-kiprasmel#9]
When using the `eslint-config-sarpik` with the latest version of cra typescript, the commands `yarn start` and `yarn build` give this error:

> .eslintrc.js » eslint-config-sarpik:
        Configuration for rule "no-unused-vars" is invalid:
        Value {"ignoreSiblings":true,"argsIgnorePattern":"res|next|^err"} should be equal to one of the allowed values.
        Value {"ignoreSiblings":true,"argsIgnorePattern":"res|next|^err"} should NOT have additional properties.
        Value {"ignoreSiblings":true,"argsIgnorePattern":"res|next|^err"} should match exactly one schema in oneOf.

overriding the rule on my .eslintrc does not change the error

```json
{
  "no-unused-vars": [
    1,
    {
      "ignoreSiblings": true,
      "argsIgnorePattern": "res"
    }
  ]
}
```

The package.json is
```json
"eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest",
      "sarpik"
    ]
  },
"dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.0.0",
    "@types/react": "^16.9.53",
    "@types/react-dom": "^16.9.8",
    "axios": "^0.21.0",
    "bootstrap": "^4.5.3",
    "node-sass": "4.14.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.0",
    "react-webcam-barcode-scanner": "^0.0.2-rc2",
    "reactstrap": "^8.7.1",
    "typescript": "3.7.3",
    "web-vitals": "^0.2.4"
  },
"devDependencies": {
    "@types/react-router-dom": "^5.1.6",
    "@types/reactstrap": "^8.7.2",
    "@typescript-eslint/eslint-plugin": "2.11.0",
    "@typescript-eslint/parser": "2.11.0",
    "babel-eslint": "10.0.3",
    "eslint": "6.8.0",
    "eslint-config-airbnb": "18.0.0",
    "eslint-config-prettier": "6.7.0",
    "eslint-config-sarpik": "0.2.8",
    "eslint-plugin-flowtype": "4.5.2",
    "eslint-plugin-html": "6.0.0",
    "eslint-plugin-import": "2.18.0",
    "eslint-plugin-jsx-a11y": "6.2.3",
    "eslint-plugin-monorepo": "0.2.1",
    "eslint-plugin-prettier": "3.0.1",
    "eslint-plugin-react": "7.14.2",
    "eslint-plugin-react-hooks": "2.3.0",
    "esprima": "4.0.1",
    "prettier": "1.16.4"
  }
```

node version: v14.15.0
npm version: 6.14.8

**Comment by kiprasmel** [comment]
hey @geoangelotti, thanks for the report.

as per [1], it seems like eslint updated the rule option's key from `ignoreSiblings` to `ignoreRestSiblings` (or otherwise I always had it wrong -- might be, but I never had any errors like you've described).

could go patch it? Apply the following command to patch it (or just change the file manually) and see if it helps. If so --  please let me know -- I'll push the fix.

```sh
patch ./node_modules/eslint-config-sarpik/.eslintrc.js <<EOF
--- .eslintrc.js
+++ .eslintrc.js
@@ -55,7 +55,7 @@
 		"no-unused-vars": [
 			1,
 			{
-				ignoreSiblings: true,
+				ignoreRestSiblings: true,
 				argsIgnorePattern: "res|next|^err",
 			},
 		],
EOF
```

[1] https://eslint.org/docs/rules/no-unused-vars#ignorerestsiblings

**Comment by geoangelotti** [comment]
Hello @kiprasmel,
Using `ignoreSiblings: true` still gives the error.
Having `ignoreRestSiblings: true` is building the correctly.
So the rule should be:
```json
{
  "no-unused-vars": [
    1,
    {
      "ignoreRestSiblings": true,
      "argsIgnorePattern": "res|next|^err"
    }
  ]
}

```
